#!/bin/bash

if command -v git-lfs >/dev/null 2>&1; then
    git lfs post-commit "$@"
else
    grep -qE "filter=lfs|diff=lfs|merge=lfs" .git/info/attributes .gitattributes && { echo -e >&2 "\nThis repository has been set up with Git LFS but Git LFS is not installed.\n"; exit 2; }
fi

if [[ -x .git/hooks/post-commit ]]; then
    .git/hooks/post-commit "$@"
    exit $?
fi
