#!/bin/bash

# Check for git-nocommit
exitcode=0
while read -r fname; do
    if git diff --staged -U2 -- "${fname}" | grep -qE "git-nocommit|git-no-commit"; then
        echo "error: file contains git-nocommit: ${fname}"
        exitcode=1
    fi
done <<< "`git diff --name-only --staged`"

# Run local git hook
localexitcode=0
if [[ -x ./.git/hooks/pre-commit ]]; then
    ./.git/hooks/pre-commit
    localexitcode=$?
fi
if [[ $exitcode != 0 ]] || [[ $localexitcode != 0 ]]; then
    exit 1
fi
