(set -o igncr) 2>/dev/null && set -o igncr; # this comment is needed
# ^ For CRLF-unfriendly systems

export SHELL=/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f /etc/bash.bashrc ]; then
	. /etc/bash.bashrc
fi

# Set helper variables
[[ $- == *i* ]] && _INTERACTIVE_SHELL=true || _INTERACTIVE_SHELL=false

shopt -q login_shell && _LOGIN_SHELL=true || _LOGIN_SHELL=false

# If we are a slurm job, don't load anything.
if [[ ! -z "${SLURM_JOB_ID}" ]]; then
	return 0
fi

. ~/.dotfiles/bash/env.sh

. ~/.dotfiles/bash/aliases.sh
. ~/.dotfiles/bash/git_config.sh 2>&1 >/dev/null
. ~/.dotfiles/bash/git_dotfiles_check.sh
. ~/.dotfiles/bash/completion.sh

. ~/.dotfiles/bash/prompt.sh

if $_INTERACTIVE_SHELL && $_LOGIN_SHELL; then
	# Info that the bashrc ran
	echo ~/.bashrc run.
fi

unset _INTERACTIVE_SHELL
unset _LOGIN_SHELL

